version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Entered the install phase..."
      - yum install -y unzip wget
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip -o terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Terraform installed successfully."

  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - cd terraform
      - terraform init \
          -backend-config="bucket=$TF_STATE_BUCKET" \
          -backend-config="key=dofs/terraform.tfstate" \
          -backend-config="region=$AWS_DEFAULT_REGION" \
          -backend-config="dynamodb_table=$TF_STATE_LOCK_TABLE"

  build:
    commands:
      - echo "Entered the build phase..."
      - echo "TF_COMMAND is $TF_COMMAND"
      - |
        if [ "$TF_COMMAND" = "plan" ]; then
          echo "Running terraform plan..."
          terraform plan \
            -out=tfplan \
            -var="aws_region=$AWS_DEFAULT_REGION" \
            -var="environment=$TF_VAR_environment" \
            -var="project_name=$TF_VAR_project_name"
          terraform show -no-color tfplan > plan_output.txt
          echo "Plan completed successfully."
        elif [ "$TF_COMMAND" = "apply" ]; then
          echo "Running terraform apply..."
          terraform plan \
            -out=tfplan \
            -var="aws_region=$AWS_DEFAULT_REGION" \
            -var="environment=$TF_VAR_environment" \
            -var="project_name=$TF_VAR_project_name"
          terraform apply -auto-approve tfplan
          echo "Apply completed successfully."
        else
          echo "Unknown TF_COMMAND: $TF_COMMAND"
          exit 1
        fi

  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: terraform

cache:
  paths:
    - '/usr/local/bin/terraform'
